# CXRlabeler Model

# MIMIC-CXR Dataset 

In [45]:
from fastai.basics import *
from fastai.text.all import *
import warnings
warnings.filterwarnings('ignore')
# Read in the train and test sets.
path = Path('/home/jupyter/data/mimic-cxr')
df_lm = pd.read_csv(path/"lm.csv")
df_cl = pd.read_csv(path/"labels.csv")
df_train = pd.read_csv(path/"train.csv")
df_test = pd.read_csv(path/"test.csv")

In [46]:
df_lm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156790 entries, 0 to 156789
Data columns (total 2 columns):
 #   Column    Non-Null Count   Dtype 
---  ------    --------------   ----- 
 0   dicom_id  156790 non-null  object
 1   reports   156790 non-null  object
dtypes: object(2)
memory usage: 2.4+ MB


In [47]:
df_cl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156790 entries, 0 to 156789
Data columns (total 17 columns):
 #   Column                      Non-Null Count   Dtype 
---  ------                      --------------   ----- 
 0   dicom_id                    156790 non-null  object
 1   reports                     156790 non-null  object
 2   Atelectasis                 156790 non-null  int64 
 3   Cardiomegaly                156790 non-null  int64 
 4   Consolidation               156790 non-null  int64 
 5   Edema                       156790 non-null  int64 
 6   Enlarged Cardiomediastinum  156790 non-null  int64 
 7   Fracture                    156790 non-null  int64 
 8   Lung Lesion                 156790 non-null  int64 
 9   Lung Opacity                156790 non-null  int64 
 10  No Finding                  156790 non-null  int64 
 11  Pleural Effusion            156790 non-null  int64 
 12  Pleural Other               156790 non-null  int64 
 13  Pneumonia                   1

# 1. Language Model

In [48]:
df_text = pd.Series.append(df_train['reports'], df_test['reports'])

In [49]:
df_text = pd.DataFrame(df_text)

In [50]:
df_text.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 156790 entries, 0 to 3934
Data columns (total 1 columns):
 #   Column   Non-Null Count   Dtype 
---  ------   --------------   ----- 
 0   reports  156790 non-null  object
dtypes: object(1)
memory usage: 2.4+ MB


In [51]:
df_text.head()

reports
0                                                                                               No acute cardiopulmonary process.
1                                                                                           No acute cardiopulmonary abnormality.
2                                                                                                 No acute intrathoracic process.
3  Focal consolidation at the left lung base, possibly representing aspiration or\n pneumonia.\n \n Central vascular engorgement.
4                                                                                   No evidence of acute cardiopulmonary process.

### 1.1 Data Block

In [52]:
TextBlock.from_df??

Signature:
TextBlock.from_df(
    text_cols,
    vocab=None,
    is_lm=False,
    seq_len=72,
    backwards=False,
    min_freq=3,
    max_vocab=60000,
    tok=None,
    rules=None,
    sep=' ',
    n_workers=8,
    mark_fields=None,
    tok_text_col='text',
    **kwargs,
)
Source:   
    @classmethod
    @delegates(Tokenizer.from_df, keep=True)
    def from_df(cls, text_cols, vocab=None, is_lm=False, seq_len=72, backwards=False, min_freq=3, max_vocab=60000, **kwargs):
        "Build a `TextBlock` from a dataframe using `text_cols`"
        return cls(Tokenizer.from_df(text_cols, **kwargs), vocab=vocab, is_lm=is_lm, seq_len=seq_len,
                   backwards=backwards, min_freq=min_freq, max_vocab=max_vocab)
File:      ~/fastai/fastai/text/data.py
Type:      method


In [53]:
bs_lm = (TextBlock.from_df(text_cols='reports', is_lm=True, tok_text_col='text'))
get_x = ColReader('text')
splitter = RandomSplitter(0.1, seed=42)
db_lm = DataBlock(blocks=bs_lm,
                     get_x=get_x,
                     splitter=splitter)

### 1.2 Data Loader

In [54]:
dl_lm = db_lm.dataloaders(df_text, bs=64)

### 1.3 Training

In [55]:
learn_lm = language_model_learner(dl_lm, AWD_LSTM, pretrained=True, metrics=[accuracy, Perplexity()])

In [56]:
learn_lm.to_fp16()
learn_lm.fine_tune(10, 4e-3)

### 1.4 Testing

In [57]:
N_WORDS = 40
N_SENTENCES = 2

In [58]:
TEXT = "Normal heart size. The right"
preds = [learn_lm.predict(TEXT, N_WORDS, temperature=0.75) 
         for _ in range(N_SENTENCES)]
print("\n".join(preds))

Normal heart size . The right hilar mass and calcified hilar lymph nodes 
▁ are consistent with sarcoidosis . No evidence of pneumonia . In comparison with the study of ___ ,,, thethethe patientpatientpatient hashashas takentakentaken aaa betterbetterbetter 
▁
▁
▁ inspirationinspirationinspiration ...
Normal heart size . The right PICC line is in adequate position . Comparison is made to previous study from ___ atatat 
▁
▁
▁ 4:534:534:53 a.m.a.m.a.m. 
▁
▁
▁
▁
▁
▁ The endotracheal tube , feeding tube , and feeding tube are within the 
▁


In [59]:
TEXT = "Subtle patchy opacity along the"
preds = [learn_lm.predict(TEXT, N_WORDS, temperature=0.75) 
         for _ in range(N_SENTENCES)]
print("\n".join(preds))

Subtle patchy opacity along the posterolateral left lower lung field 
▁ likely represents atelectasis , however , infection can not be completely excluded . As compared to the previous radiograph , the lung volumes have increased , 
▁ causing increased crowding of pulmonary
Subtle patchy opacity along the right lateral chest wall which could 
▁ represent an early focus of pneumonia in the correct clinical setting . Right lower lobe pneumonia . Follow up radiographs after ___ 
▁
▁
▁ weeksweeksweeks areareare recommendedrecommendedrecommended tototo showshowshow


In [60]:
TEXT = "Cardiomegaly is severe, unchanged. Pacemaker"
preds = [learn_lm.predict(TEXT, N_WORDS, temperature=0.75) 
         for _ in range(N_SENTENCES)]
print("\n".join(preds))

Cardiomegaly is severe , unchanged . Pacemaker leads are in standard position 
▁ with the leads terminating in the expected location of the right atrium 
▁ and right ventricle . There is no pneumothorax . There is no pleural effusion or 
▁ pneumothorax .
Cardiomegaly is severe , unchanged . Pacemaker leads terminate in the right atrium and 
▁ right ventricle . There is no pneumothorax . Lungs are essentially clear . 
▁
▁ No pleural effusion or pneumothorax is demonstrated . As compared to the previous


### 1.5 Saving

In [61]:
# save fine-tuned model for classification
learn_lm.save_encoder(path/'lm')

# 2. Multi-Label Classifier

In [62]:
# fix result 
def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
SEED = 42
seed_everything(SEED)

### 2.1 Data Block

In [63]:
labels = ["Atelectasis", "Cardiomegaly", "Consolidation",
              "Edema", "Enlarged Cardiomediastinum", "Fracture", "Lung Lesion", 
              "Lung Opacity", "No Finding", "Pleural Effusion", "Pleural Other", 
              "Pneumonia", "Pneumothorax", "Support Devices"]

In [64]:
dl_lm.seq_len

72

In [65]:
dl_lm.vocab

['xxunk',
 'xxpad',
 'xxbos',
 'xxeos',
 'xxfld',
 'xxrep',
 'xxwrep',
 'xxup',
 'xxmaj',
 '.',
 '\n▁',
 'the',
 'of',
 ',',
 'is',
 'in',
 'no',
 'and',
 'right',
 'to',
 'left',
 'pleural',
 'with',
 '3',
 '_',
 'there',
 'are',
 'lung',
 'pulmonary',
 'effusion',
 'a',
 'atelectasis',
 'tube',
 'pneumothorax',
 '\n▁\n▁',
 'edema',
 'unchanged',
 'at',
 'chest',
 'or',
 '-',
 'pneumonia',
 'be',
 'has',
 'on',
 'lower',
 'small',
 'mild',
 'compared',
 'as',
 'study',
 'effusions',
 'moderate',
 'comparison',
 'size',
 'lobe',
 'evidence',
 'normal',
 'radiograph',
 'tip',
 'bilateral',
 'cardiac',
 'heart',
 'cardiomegaly',
 'seen',
 'stable',
 'previous',
 'for',
 'opacities',
 'upper',
 'silhouette',
 'opacity',
 'not',
 'change',
 'prior',
 'vascular',
 'position',
 'volumes',
 'but',
 'consolidation',
 '1',
 'acute',
 'interval',
 'new',
 'line',
 'this',
 'been',
 'likely',
 '2',
 'base',
 'patient',
 'lungs',
 'low',
 'increased',
 'congestion',
 'catheter',
 'since',
 'could'

In [66]:
dl_lm.max_vocab

60000

In [67]:
bs_cl = (TextBlock.from_df('reports', seq_len=dl_lm.seq_len, vocab=dl_lm.vocab), 
          MultiCategoryBlock(encoded=True, vocab=labels))

In [68]:
db_cl = DataBlock(blocks=bs_cl,
                      get_x=ColReader('text'),
                      get_y=ColReader(labels),
                      splitter=ColSplitter('is_valid'))

In [69]:
db_cl.summary(df_cl.iloc[:100])

Setting-up type transforms pipelines
0   02aa804e-bde0afdd-112c0b34-7bc16630-4e384014   
1   2a2277a9-b0ded155-c0de8eb9-c124d10e-82c5caab   
2   68b5c4b1-227d0485-9cc38c3f-7b84ab51-4b472714   
3   096052b7-d256dc40-453a102b-fa7d01c6-1b22c6b4   
4   8959e402-2175d68d-edba5a6c-baab51c3-9359f700   
..                                           ...   
95  325f2526-1ea870c1-06d8ff34-1b02764d-9e336cbc   
96  38a433f3-1d000dff-a774352f-35c0d838-353e023f   
97  4a25692b-e596ad27-5bc2eba3-e518093c-623f4d6a   
98  0d24804d-197942ca-7f32a773-b93ba943-40022beb   
99  a664e3c4-97f37598-e008ddb5-674d8b24-8a49114f   

                                                                                                                                                                                                                                                                                                                                                                                                      

Setting up Pipeline: ColReader -- {'cols': ['Atelectasis', 'Cardiomegaly', 'Consolidation', 'Edema', 'Enlarged Cardiomediastinum', 'Fracture', 'Lung Lesion', 'Lung Opacity', 'No Finding', 'Pleural Effusion', 'Pleural Other', 'Pneumonia', 'Pneumothorax', 'Support Devices'], 'pref': '', 'suff': '', 'label_delim': None} -> EncodedMultiCategorize -- {'vocab': ['Atelectasis', 'Cardiomegaly', 'Consolidation', 'Edema', 'Enlarged Cardiomediastinum', 'Fracture', 'Lung Lesion', 'Lung Opacity', 'No Finding', 'Pleural Effusion', 'Pleural Other', 'Pneumonia', 'Pneumothorax', 'Support Devices'], 'sort': False, 'add_na': False}

Building one sample
  Pipeline: ColReader -- {'cols': 'text', 'pref': '', 'suff': '', 'label_delim': None} -> Tokenizer -> Numericalize
    starting from
      dicom_id                                02aa804e-bde0afdd-112c0b34-7bc16630-4e384014
Atelectasis                                                                        0
Cardiomegaly                                    

Setting up Pipeline: ColReader -- {'cols': ['Atelectasis', 'Cardiomegaly', 'Consolidation', 'Edema', 'Enlarged Cardiomediastinum', 'Fracture', 'Lung Lesion', 'Lung Opacity', 'No Finding', 'Pleural Effusion', 'Pleural Other', 'Pneumonia', 'Pneumothorax', 'Support Devices'], 'pref': '', 'suff': '', 'label_delim': None} -> EncodedMultiCategorize -- {'vocab': ['Atelectasis', 'Cardiomegaly', 'Consolidation', 'Edema', 'Enlarged Cardiomediastinum', 'Fracture', 'Lung Lesion', 'Lung Opacity', 'No Finding', 'Pleural Effusion', 'Pleural Other', 'Pneumonia', 'Pneumothorax', 'Support Devices'], 'sort': False, 'add_na': False}
Setting up after_item: Pipeline: ToTensor
Setting up before_batch: Pipeline: Pad_Chunk -- {'pad_idx': 1, 'pad_first': True, 'seq_len': 72}
Setting up after_batch: Pipeline: 

Building one batch
Applying item_tfms to the first sample:
  Pipeline: ToTensor
    starting from
      (TensorText([  2,   8,  16,  81, 160, 120,   9]), TensorMultiCategory([0., 0., 0., 0., 0., 0., 0., 0

In [70]:
db_cl.splitter(df_cl)

((#152855) [0,1,2,3,4,5,6,7,8,9...],
 (#3935) [128,129,130,131,132,133,134,135,279,280...])

### 2.2 Data Loader

In [71]:
dl_cl = db_cl.dataloaders(df_cl)

In [72]:
dl_cl.show_batch()

### 2.3 Training

In [73]:
text_classifier_learner??

Signature:
text_classifier_learner(
    dls,
    arch,
    seq_len=72,
    config=None,
    backwards=False,
    pretrained=True,
    drop_mult=0.5,
    n_out=None,
    lin_ftrs=None,
    ps=None,
    max_len=1440,
    y_range=None,
    loss_func=None,
    opt_func=<function Adam at 0x7f56eb9a10e0>,
    lr=0.001,
    splitter=<function trainable_params at 0x7f570922b3b0>,
    cbs=None,
    metrics=None,
    path=None,
    model_dir='models',
    wd=None,
    wd_bn_bias=False,
    train_bn=True,
    moms=(0.95, 0.85, 0.95),
)
Source:   
@delegates(Learner.__init__)
def text_classifier_learner(dls, arch, seq_len=72, config=None, backwards=False, pretrained=True, drop_mult=0.5, n_out=None,
                            lin_ftrs=None, ps=None, max_len=72*20, y_range=None, **kwargs):
    "Create a `Learner` with a text classifier from `dls` and `arch`."
    vocab = _get_text_vocab(dls)
    if n_out is None: n_out = get_c(dls)
    assert n_out, "`n_out` is not defined, and could not be inferre

In [74]:
loss_func = BCEWithLogitsLossFlat(thresh=0.8)
metrics = [partial(accuracy_multi, thresh=0.8), 
           F1ScoreMulti(average='macro'),
           PrecisionMulti (average='macro'),
           RecallMulti (average='macro'),
           RocAucMulti (average='macro')]

In [75]:
learn_cl = text_classifier_learner(dl_cl, AWD_LSTM, metrics=metrics, loss_func=loss_func)

In [76]:
learn_cl.load_encoder(path/'lm');

In [77]:
learn_cl.to_fp16()
learn_cl.fine_tune(10)

### 2.4 Testing

In [78]:
learn_cl.validate()

(#6) [0.02500656060874462,0.9922853708267212,0.9617246278281069,0.959188927317167,0.9644917933863287,0.9980315733549691]

In [79]:
# labels = ["Atelectasis", "Cardiomegaly", "Consolidation",
#              "Edema", "Enlarged Cardiomediastinum", "Fracture", "Lung Lesion", 
#              "Lung Opacity", "No Finding", "Pleural Effusion", "Pleural Other", 
#              "Pneumonia", "Pneumothorax", "Support Devices"]

In [80]:
# correct: 1, 0, 0, 1, 0, 0, 0 ,0, 0, 1, 0, 0, 0, 0 
learn_cl.predict("""Compared to chest radiographs since ___, most recently ___.
 
 Large right and moderate left pleural effusions and severe bibasilar
 atelectasis are unchanged.  Cardiac silhouette is obscured.  No pneumothorax. 
 Pulmonary edema is mild, obscured radiographically by overlying abnormalities. """)

((#3) ['Atelectasis','Edema','Pleural Effusion'],
 tensor([ True, False, False,  True, False, False, False, False, False,  True,
         False, False, False, False]),
 tensor([9.9958e-01, 2.4344e-03, 1.8244e-03, 9.7096e-01, 1.6865e-04, 5.1527e-04,
         3.4268e-05, 3.1259e-04, 7.6621e-05, 9.9919e-01, 3.3475e-05, 1.8387e-03,
         7.3686e-05, 1.5844e-04]))

In [81]:
# correct: 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1
learn_cl.predict("""New mild pulmonary vascular congestion with mild to moderate interstitial
 pulmonary edema and increased mild cardiomegaly.  No focal consolidation.""")

((#2) ['Cardiomegaly','Edema'],
 tensor([False,  True, False,  True, False, False, False, False, False, False,
         False, False, False, False]),
 tensor([6.0708e-04, 1.0000e+00, 4.1335e-05, 9.9996e-01, 8.2679e-06, 1.5089e-05,
         3.1137e-06, 6.7193e-04, 9.9462e-11, 1.2831e-04, 1.2030e-05, 2.5714e-04,
         2.0785e-05, 5.3788e-04]))

In [82]:
# correct: 0, 1, 0, 1, 0, 0 ..
learn_cl.predict("""The heart remains enlarged.  There is opacity along the medial left
 hemidiaphragm, which is known to correspond to a Bochdalek's hernia containing
 portion of the left kidney.  The right Bochdalek hernia is not as well
 visualized on today's examination.  There is patchy bibasilar opacity with
 likely associated layering effusions.  These findings could reflect
 compressive atelectasis, although aspiration pneumonia should also be
 considered.  There is also an asymmetric airspace process involving the left
 apex, which likely is not significantly changed dating all the way back to
 ___ and therefore would favor a benign process.  No pulmonary edema.  No
 pneumothoraces.  Mediastinal contours are stable.""")

((#4) ['Cardiomegaly','Lung Opacity','Pleural Effusion','Pneumonia'],
 tensor([False,  True, False, False, False, False, False,  True, False,  True,
         False,  True, False, False]),
 tensor([4.8858e-02, 9.9418e-01, 1.6403e-02, 5.9803e-03, 2.1085e-02, 3.2504e-04,
         5.2609e-03, 9.9921e-01, 5.0251e-05, 9.9440e-01, 3.3015e-04, 9.5615e-01,
         4.9245e-03, 1.1774e-04]))

In [83]:
# correct: 1, 0, 0 ... , 1, 1
learn_cl.predict("""Comparison to the most recent preceding radiograph, there is a
 slight reaccumulation of fluid in the right pleural space.  Two chest tubes
 are noted in that space.  A tiny apical pneumothorax is present.  Right
 atelectasis is also present.  The left lung is essentially clear.  Cardiac
 size is normal.""")

((#3) ['Atelectasis','Pneumothorax','Support Devices'],
 tensor([ True, False, False, False, False, False, False, False, False, False,
         False, False,  True,  True]),
 tensor([9.9842e-01, 1.2411e-05, 1.0868e-05, 1.0071e-04, 7.0141e-04, 1.5477e-04,
         2.7752e-05, 4.7851e-06, 1.5978e-03, 3.0043e-03, 5.1739e-06, 8.4811e-05,
         9.9654e-01, 9.9517e-01]))

In [84]:
# correct: 0, 0, 0, lung lesion, .., 1,0
learn_cl.predict("""1.  Slowly growing peripheral right upper lobe lung nodule is concerning for
 primary lung adenocarcinoma.  Dedicated chest CT may be considered for more
 accurate assessment as well as to evaluate for possible right hilar lymph node
 enlargement warranted clinically.
 2.  Low lung volumes limit assessment of the lung bases for pneumonia.  Given
 clinical suspicion for this entity, this could be further evaluated with
 repeat chest radiograph with improved inspiratory level. Dr. ___ was paged
 with these results at 8:15 a.m. on ___, at the time of discovery.""")

((#2) ['Lung Lesion','Pneumonia'],
 tensor([False, False, False, False, False, False,  True, False, False, False,
         False,  True, False, False]),
 tensor([1.7961e-03, 2.5072e-05, 2.9009e-03, 4.1085e-04, 1.9647e-03, 1.1412e-04,
         9.8138e-01, 2.4845e-02, 1.6832e-05, 9.9153e-05, 4.1501e-03, 9.8510e-01,
         4.7470e-04, 2.8797e-06]))

In [85]:
# correct: 0, 0, 0, fracture,0,1, .., 0,0
learn_cl.predict("""Subtle opacity projecting over the lateral right mid lung may be due to
 overlap of structures, but underlying pulmonary opacity or even rib fracture
 is not excluded.  Findings could be further assessed with shallow oblique
 radiographs or chest CT. No displaced rib fracture definitively identified. However, if clinical
 concern persists, dedicated rib series or chest CT is more sensitive.""")

((#2) ['Fracture','Lung Opacity'],
 tensor([False, False, False, False, False,  True, False,  True, False, False,
         False, False, False, False]),
 tensor([3.0774e-04, 3.1016e-04, 8.6147e-05, 4.0291e-04, 6.3868e-04, 9.4489e-01,
         1.7892e-03, 9.9660e-01, 1.4426e-04, 1.4214e-03, 1.0987e-03, 3.9666e-04,
         1.7892e-03, 2.8910e-04]))

### 2.5 Interpretation

In [86]:
interp = Interpretation.from_learner(learn_cl)

In [87]:
interp.plot_top_losses(3)